/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteRouteImport } from './routes/(protected)/_layout/route'
import { Route as protectedLayoutIndexRouteImport } from './routes/(protected)/_layout/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as protectedLayoutWhatsNewIndexRouteImport } from './routes/(protected)/_layout/whats-new/index'
import { Route as protectedLayoutSupportIndexRouteImport } from './routes/(protected)/_layout/support/index'
import { Route as protectedLayoutReferAndEarnIndexRouteImport } from './routes/(protected)/_layout/refer-and-earn/index'
import { Route as protectedLayoutProfileIndexRouteImport } from './routes/(protected)/_layout/profile/index'
import { Route as protectedLayoutPracticeInterviewIndexRouteImport } from './routes/(protected)/_layout/practice-interview/index'
import { Route as protectedLayoutMasaiverseIndexRouteImport } from './routes/(protected)/_layout/masaiverse/index'
import { Route as protectedLayoutDiscussionsIndexRouteImport } from './routes/(protected)/_layout/discussions/index'
import { Route as protectedLayoutCoursesIndexRouteImport } from './routes/(protected)/_layout/courses/index'
import { Route as protectedLayoutChatIndexRouteImport } from './routes/(protected)/_layout/chat/index'
import { Route as protectedLayoutBookmarkIndexRouteImport } from './routes/(protected)/_layout/bookmark/index'
import { Route as protectedLayoutAnnouncementsIndexRouteImport } from './routes/(protected)/_layout/announcements/index'
import { Route as protectedLayoutSupportSupportIdIndexRouteImport } from './routes/(protected)/_layout/support/$supportId/index'
import { Route as protectedLayoutDiscussionsCreateIndexRouteImport } from './routes/(protected)/_layout/discussions/create/index'
import { Route as protectedLayoutDiscussionsDiscussionIdIndexRouteImport } from './routes/(protected)/_layout/discussions/$discussionId/index'
import { Route as protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteImport } from './routes/(protected)/_layout/courses/$courseId/_courseTabLayout/route'
import { Route as protectedLayoutCoursesCourseIdCourseTabLayoutIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/_courseTabLayout/index'
import { Route as protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteImport } from './routes/(protected)/_layout/courses/$courseId/lectures_/$lectureId/route'
import { Route as protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteImport } from './routes/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/route'
import { Route as protectedLayoutCoursesCourseIdResourcesResourceIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/resources_/$resourceId/index'
import { Route as protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/index'
import { Route as protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/announcements_/$announcementId/index'
import { Route as protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/_courseTabLayout/resources/index'
import { Route as protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/_courseTabLayout/lectures/index'
import { Route as protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/_courseTabLayout/assignments/index'
import { Route as protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/index'
import { Route as protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/index'
import { Route as protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/create/index'
import { Route as protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/$discussionId/index'
import { Route as protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/create/index'
import { Route as protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/$discussionId/index'

const protectedLayoutRouteRoute = protectedLayoutRouteRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutWhatsNewIndexRoute =
  protectedLayoutWhatsNewIndexRouteImport.update({
    id: '/whats-new/',
    path: '/whats-new/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutSupportIndexRoute =
  protectedLayoutSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutReferAndEarnIndexRoute =
  protectedLayoutReferAndEarnIndexRouteImport.update({
    id: '/refer-and-earn/',
    path: '/refer-and-earn/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutProfileIndexRoute =
  protectedLayoutProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutPracticeInterviewIndexRoute =
  protectedLayoutPracticeInterviewIndexRouteImport.update({
    id: '/practice-interview/',
    path: '/practice-interview/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutMasaiverseIndexRoute =
  protectedLayoutMasaiverseIndexRouteImport.update({
    id: '/masaiverse/',
    path: '/masaiverse/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutDiscussionsIndexRoute =
  protectedLayoutDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesIndexRoute =
  protectedLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutChatIndexRoute =
  protectedLayoutChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutBookmarkIndexRoute =
  protectedLayoutBookmarkIndexRouteImport.update({
    id: '/bookmark/',
    path: '/bookmark/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutAnnouncementsIndexRoute =
  protectedLayoutAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutSupportSupportIdIndexRoute =
  protectedLayoutSupportSupportIdIndexRouteImport.update({
    id: '/support/$supportId/',
    path: '/support/$supportId/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutDiscussionsCreateIndexRoute =
  protectedLayoutDiscussionsCreateIndexRouteImport.update({
    id: '/discussions/create/',
    path: '/discussions/create/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutDiscussionsDiscussionIdIndexRoute =
  protectedLayoutDiscussionsDiscussionIdIndexRouteImport.update({
    id: '/discussions/$discussionId/',
    path: '/discussions/$discussionId/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute =
  protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteImport.update({
    id: '/courses/$courseId/_courseTabLayout',
    path: '/courses/$courseId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute =
  protectedLayoutCoursesCourseIdCourseTabLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute =
  protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteImport.update({
    id: '/courses/$courseId/lectures_/$lectureId',
    path: '/courses/$courseId/lectures/$lectureId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute =
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteImport.update({
    id: '/courses/$courseId/assignments_/$assignmentId',
    path: '/courses/$courseId/assignments/$assignmentId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute =
  protectedLayoutCoursesCourseIdResourcesResourceIdIndexRouteImport.update({
    id: '/courses/$courseId/resources_/$resourceId/',
    path: '/courses/$courseId/resources/$resourceId/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute =
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute =
  protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRouteImport.update(
    {
      id: '/courses/$courseId/announcements_/$announcementId/',
      path: '/courses/$courseId/announcements/$announcementId/',
      getParentRoute: () => protectedLayoutRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute =
  protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRouteImport.update(
    {
      id: '/resources/',
      path: '/resources/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute =
  protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRouteImport.update({
    id: '/lectures/',
    path: '/lectures/',
    getParentRoute: () =>
      protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute =
  protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRouteImport.update(
    {
      id: '/assignments/',
      path: '/assignments/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute =
  protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRouteImport.update(
    {
      id: '/discussions/',
      path: '/discussions/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute =
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRouteImport.update(
    {
      id: '/discussions/',
      path: '/discussions/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute =
  protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRouteImport.update(
    {
      id: '/discussions/create/',
      path: '/discussions/create/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute =
  protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRouteImport.update(
    {
      id: '/discussions/$discussionId/',
      path: '/discussions/$discussionId/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute =
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRouteImport.update(
    {
      id: '/discussions/create/',
      path: '/discussions/create/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute,
    } as any,
  )
const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute =
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRouteImport.update(
    {
      id: '/discussions/$discussionId/',
      path: '/discussions/$discussionId/',
      getParentRoute: () =>
        protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/login/': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/announcements/': typeof protectedLayoutAnnouncementsIndexRoute
  '/bookmark/': typeof protectedLayoutBookmarkIndexRoute
  '/chat/': typeof protectedLayoutChatIndexRoute
  '/courses/': typeof protectedLayoutCoursesIndexRoute
  '/discussions/': typeof protectedLayoutDiscussionsIndexRoute
  '/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
  '/practice-interview/': typeof protectedLayoutPracticeInterviewIndexRoute
  '/profile/': typeof protectedLayoutProfileIndexRoute
  '/refer-and-earn/': typeof protectedLayoutReferAndEarnIndexRoute
  '/support/': typeof protectedLayoutSupportIndexRoute
  '/whats-new/': typeof protectedLayoutWhatsNewIndexRoute
  '/courses/$courseId': typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteWithChildren
  '/discussions/$discussionId/': typeof protectedLayoutDiscussionsDiscussionIdIndexRoute
  '/discussions/create/': typeof protectedLayoutDiscussionsCreateIndexRoute
  '/support/$supportId/': typeof protectedLayoutSupportSupportIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteWithChildren
  '/courses/$courseId/lectures/$lectureId': typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteWithChildren
  '/courses/$courseId/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute
  '/courses/$courseId/assignments/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute
  '/courses/$courseId/lectures/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute
  '/courses/$courseId/resources/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute
  '/courses/$courseId/announcements/$announcementId/': typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  '/courses/$courseId/resources/$resourceId/': typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId/discussions/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute
  '/courses/$courseId/lectures/$lectureId/discussions/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute
  '/courses/$courseId/assignments/$assignmentId/discussions/$discussionId/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId/discussions/create/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute
  '/courses/$courseId/lectures/$lectureId/discussions/$discussionId/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute
  '/courses/$courseId/lectures/$lectureId/discussions/create/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/announcements': typeof protectedLayoutAnnouncementsIndexRoute
  '/bookmark': typeof protectedLayoutBookmarkIndexRoute
  '/chat': typeof protectedLayoutChatIndexRoute
  '/courses': typeof protectedLayoutCoursesIndexRoute
  '/discussions': typeof protectedLayoutDiscussionsIndexRoute
  '/masaiverse': typeof protectedLayoutMasaiverseIndexRoute
  '/practice-interview': typeof protectedLayoutPracticeInterviewIndexRoute
  '/profile': typeof protectedLayoutProfileIndexRoute
  '/refer-and-earn': typeof protectedLayoutReferAndEarnIndexRoute
  '/support': typeof protectedLayoutSupportIndexRoute
  '/whats-new': typeof protectedLayoutWhatsNewIndexRoute
  '/discussions/$discussionId': typeof protectedLayoutDiscussionsDiscussionIdIndexRoute
  '/discussions/create': typeof protectedLayoutDiscussionsCreateIndexRoute
  '/support/$supportId': typeof protectedLayoutSupportSupportIdIndexRoute
  '/courses/$courseId/lectures/$lectureId': typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteWithChildren
  '/courses/$courseId': typeof protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute
  '/courses/$courseId/assignments': typeof protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute
  '/courses/$courseId/lectures': typeof protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute
  '/courses/$courseId/resources': typeof protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute
  '/courses/$courseId/announcements/$announcementId': typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  '/courses/$courseId/resources/$resourceId': typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId/discussions': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute
  '/courses/$courseId/lectures/$lectureId/discussions': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute
  '/courses/$courseId/assignments/$assignmentId/discussions/$discussionId': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId/discussions/create': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute
  '/courses/$courseId/lectures/$lectureId/discussions/$discussionId': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute
  '/courses/$courseId/lectures/$lectureId/discussions/create': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/_layout': typeof protectedLayoutRouteRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/_layout/announcements/': typeof protectedLayoutAnnouncementsIndexRoute
  '/(protected)/_layout/bookmark/': typeof protectedLayoutBookmarkIndexRoute
  '/(protected)/_layout/chat/': typeof protectedLayoutChatIndexRoute
  '/(protected)/_layout/courses/': typeof protectedLayoutCoursesIndexRoute
  '/(protected)/_layout/discussions/': typeof protectedLayoutDiscussionsIndexRoute
  '/(protected)/_layout/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
  '/(protected)/_layout/practice-interview/': typeof protectedLayoutPracticeInterviewIndexRoute
  '/(protected)/_layout/profile/': typeof protectedLayoutProfileIndexRoute
  '/(protected)/_layout/refer-and-earn/': typeof protectedLayoutReferAndEarnIndexRoute
  '/(protected)/_layout/support/': typeof protectedLayoutSupportIndexRoute
  '/(protected)/_layout/whats-new/': typeof protectedLayoutWhatsNewIndexRoute
  '/(protected)/_layout/courses/$courseId/_courseTabLayout': typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteWithChildren
  '/(protected)/_layout/discussions/$discussionId/': typeof protectedLayoutDiscussionsDiscussionIdIndexRoute
  '/(protected)/_layout/discussions/create/': typeof protectedLayoutDiscussionsCreateIndexRoute
  '/(protected)/_layout/support/$supportId/': typeof protectedLayoutSupportSupportIdIndexRoute
  '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteWithChildren
  '/(protected)/_layout/courses/$courseId/lectures_/$lectureId': typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteWithChildren
  '/(protected)/_layout/courses/$courseId/_courseTabLayout/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute
  '/(protected)/_layout/courses/$courseId/_courseTabLayout/assignments/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute
  '/(protected)/_layout/courses/$courseId/_courseTabLayout/lectures/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute
  '/(protected)/_layout/courses/$courseId/_courseTabLayout/resources/': typeof protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute
  '/(protected)/_layout/courses/$courseId/announcements_/$announcementId/': typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  '/(protected)/_layout/courses/$courseId/resources_/$resourceId/': typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
  '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute
  '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute
  '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/$discussionId/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute
  '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/create/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute
  '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/$discussionId/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute
  '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/create/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login/'
    | '/'
    | '/announcements/'
    | '/bookmark/'
    | '/chat/'
    | '/courses/'
    | '/discussions/'
    | '/masaiverse/'
    | '/practice-interview/'
    | '/profile/'
    | '/refer-and-earn/'
    | '/support/'
    | '/whats-new/'
    | '/courses/$courseId'
    | '/discussions/$discussionId/'
    | '/discussions/create/'
    | '/support/$supportId/'
    | '/courses/$courseId/assignments/$assignmentId'
    | '/courses/$courseId/lectures/$lectureId'
    | '/courses/$courseId/'
    | '/courses/$courseId/assignments/'
    | '/courses/$courseId/lectures/'
    | '/courses/$courseId/resources/'
    | '/courses/$courseId/announcements/$announcementId/'
    | '/courses/$courseId/assignments/$assignmentId/'
    | '/courses/$courseId/resources/$resourceId/'
    | '/courses/$courseId/assignments/$assignmentId/discussions/'
    | '/courses/$courseId/lectures/$lectureId/discussions/'
    | '/courses/$courseId/assignments/$assignmentId/discussions/$discussionId/'
    | '/courses/$courseId/assignments/$assignmentId/discussions/create/'
    | '/courses/$courseId/lectures/$lectureId/discussions/$discussionId/'
    | '/courses/$courseId/lectures/$lectureId/discussions/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/announcements'
    | '/bookmark'
    | '/chat'
    | '/courses'
    | '/discussions'
    | '/masaiverse'
    | '/practice-interview'
    | '/profile'
    | '/refer-and-earn'
    | '/support'
    | '/whats-new'
    | '/discussions/$discussionId'
    | '/discussions/create'
    | '/support/$supportId'
    | '/courses/$courseId/lectures/$lectureId'
    | '/courses/$courseId'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/lectures'
    | '/courses/$courseId/resources'
    | '/courses/$courseId/announcements/$announcementId'
    | '/courses/$courseId/assignments/$assignmentId'
    | '/courses/$courseId/resources/$resourceId'
    | '/courses/$courseId/assignments/$assignmentId/discussions'
    | '/courses/$courseId/lectures/$lectureId/discussions'
    | '/courses/$courseId/assignments/$assignmentId/discussions/$discussionId'
    | '/courses/$courseId/assignments/$assignmentId/discussions/create'
    | '/courses/$courseId/lectures/$lectureId/discussions/$discussionId'
    | '/courses/$courseId/lectures/$lectureId/discussions/create'
  id:
    | '__root__'
    | '/(protected)/_layout'
    | '/(auth)/login/'
    | '/(protected)/_layout/'
    | '/(protected)/_layout/announcements/'
    | '/(protected)/_layout/bookmark/'
    | '/(protected)/_layout/chat/'
    | '/(protected)/_layout/courses/'
    | '/(protected)/_layout/discussions/'
    | '/(protected)/_layout/masaiverse/'
    | '/(protected)/_layout/practice-interview/'
    | '/(protected)/_layout/profile/'
    | '/(protected)/_layout/refer-and-earn/'
    | '/(protected)/_layout/support/'
    | '/(protected)/_layout/whats-new/'
    | '/(protected)/_layout/courses/$courseId/_courseTabLayout'
    | '/(protected)/_layout/discussions/$discussionId/'
    | '/(protected)/_layout/discussions/create/'
    | '/(protected)/_layout/support/$supportId/'
    | '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId'
    | '/(protected)/_layout/courses/$courseId/lectures_/$lectureId'
    | '/(protected)/_layout/courses/$courseId/_courseTabLayout/'
    | '/(protected)/_layout/courses/$courseId/_courseTabLayout/assignments/'
    | '/(protected)/_layout/courses/$courseId/_courseTabLayout/lectures/'
    | '/(protected)/_layout/courses/$courseId/_courseTabLayout/resources/'
    | '/(protected)/_layout/courses/$courseId/announcements_/$announcementId/'
    | '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/'
    | '/(protected)/_layout/courses/$courseId/resources_/$resourceId/'
    | '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/'
    | '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/'
    | '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/$discussionId/'
    | '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/create/'
    | '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/$discussionId/'
    | '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRouteRoute: typeof protectedLayoutRouteRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/whats-new/': {
      id: '/(protected)/_layout/whats-new/'
      path: '/whats-new'
      fullPath: '/whats-new/'
      preLoaderRoute: typeof protectedLayoutWhatsNewIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/support/': {
      id: '/(protected)/_layout/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof protectedLayoutSupportIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/refer-and-earn/': {
      id: '/(protected)/_layout/refer-and-earn/'
      path: '/refer-and-earn'
      fullPath: '/refer-and-earn/'
      preLoaderRoute: typeof protectedLayoutReferAndEarnIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/profile/': {
      id: '/(protected)/_layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedLayoutProfileIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/practice-interview/': {
      id: '/(protected)/_layout/practice-interview/'
      path: '/practice-interview'
      fullPath: '/practice-interview/'
      preLoaderRoute: typeof protectedLayoutPracticeInterviewIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/masaiverse/': {
      id: '/(protected)/_layout/masaiverse/'
      path: '/masaiverse'
      fullPath: '/masaiverse/'
      preLoaderRoute: typeof protectedLayoutMasaiverseIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/discussions/': {
      id: '/(protected)/_layout/discussions/'
      path: '/discussions'
      fullPath: '/discussions/'
      preLoaderRoute: typeof protectedLayoutDiscussionsIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/': {
      id: '/(protected)/_layout/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof protectedLayoutCoursesIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/chat/': {
      id: '/(protected)/_layout/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof protectedLayoutChatIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/bookmark/': {
      id: '/(protected)/_layout/bookmark/'
      path: '/bookmark'
      fullPath: '/bookmark/'
      preLoaderRoute: typeof protectedLayoutBookmarkIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/announcements/': {
      id: '/(protected)/_layout/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof protectedLayoutAnnouncementsIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/support/$supportId/': {
      id: '/(protected)/_layout/support/$supportId/'
      path: '/support/$supportId'
      fullPath: '/support/$supportId/'
      preLoaderRoute: typeof protectedLayoutSupportSupportIdIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/discussions/create/': {
      id: '/(protected)/_layout/discussions/create/'
      path: '/discussions/create'
      fullPath: '/discussions/create/'
      preLoaderRoute: typeof protectedLayoutDiscussionsCreateIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/discussions/$discussionId/': {
      id: '/(protected)/_layout/discussions/$discussionId/'
      path: '/discussions/$discussionId'
      fullPath: '/discussions/$discussionId/'
      preLoaderRoute: typeof protectedLayoutDiscussionsDiscussionIdIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/_courseTabLayout': {
      id: '/(protected)/_layout/courses/$courseId/_courseTabLayout'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/_courseTabLayout/': {
      id: '/(protected)/_layout/courses/$courseId/_courseTabLayout/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/lectures_/$lectureId': {
      id: '/(protected)/_layout/courses/$courseId/lectures_/$lectureId'
      path: '/courses/$courseId/lectures/$lectureId'
      fullPath: '/courses/$courseId/lectures/$lectureId'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId': {
      id: '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId'
      path: '/courses/$courseId/assignments/$assignmentId'
      fullPath: '/courses/$courseId/assignments/$assignmentId'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/resources_/$resourceId/': {
      id: '/(protected)/_layout/courses/$courseId/resources_/$resourceId/'
      path: '/courses/$courseId/resources/$resourceId'
      fullPath: '/courses/$courseId/resources/$resourceId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/': {
      id: '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/'
      path: '/'
      fullPath: '/courses/$courseId/assignments/$assignmentId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/announcements_/$announcementId/': {
      id: '/(protected)/_layout/courses/$courseId/announcements_/$announcementId/'
      path: '/courses/$courseId/announcements/$announcementId'
      fullPath: '/courses/$courseId/announcements/$announcementId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/_courseTabLayout/resources/': {
      id: '/(protected)/_layout/courses/$courseId/_courseTabLayout/resources/'
      path: '/resources'
      fullPath: '/courses/$courseId/resources/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/_courseTabLayout/lectures/': {
      id: '/(protected)/_layout/courses/$courseId/_courseTabLayout/lectures/'
      path: '/lectures'
      fullPath: '/courses/$courseId/lectures/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/_courseTabLayout/assignments/': {
      id: '/(protected)/_layout/courses/$courseId/_courseTabLayout/assignments/'
      path: '/assignments'
      fullPath: '/courses/$courseId/assignments/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/': {
      id: '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/'
      path: '/discussions'
      fullPath: '/courses/$courseId/lectures/$lectureId/discussions/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/': {
      id: '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/'
      path: '/discussions'
      fullPath: '/courses/$courseId/assignments/$assignmentId/discussions/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/create/': {
      id: '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/create/'
      path: '/discussions/create'
      fullPath: '/courses/$courseId/lectures/$lectureId/discussions/create/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/$discussionId/': {
      id: '/(protected)/_layout/courses/$courseId/lectures_/$lectureId/discussions/$discussionId/'
      path: '/discussions/$discussionId'
      fullPath: '/courses/$courseId/lectures/$lectureId/discussions/$discussionId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/create/': {
      id: '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/create/'
      path: '/discussions/create'
      fullPath: '/courses/$courseId/assignments/$assignmentId/discussions/create/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/$discussionId/': {
      id: '/(protected)/_layout/courses/$courseId/assignments_/$assignmentId/discussions/$discussionId/'
      path: '/discussions/$discussionId'
      fullPath: '/courses/$courseId/assignments/$assignmentId/discussions/$discussionId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute
    }
  }
}

interface protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteChildren {
  protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute
  protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute
  protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute
  protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute
}

const protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteChildren: protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteChildren =
  {
    protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute:
      protectedLayoutCoursesCourseIdCourseTabLayoutIndexRoute,
    protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute:
      protectedLayoutCoursesCourseIdCourseTabLayoutAssignmentsIndexRoute,
    protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute:
      protectedLayoutCoursesCourseIdCourseTabLayoutLecturesIndexRoute,
    protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute:
      protectedLayoutCoursesCourseIdCourseTabLayoutResourcesIndexRoute,
  }

const protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteWithChildren =
  protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute._addFileChildren(
    protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteChildren,
  )

interface protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteChildren {
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute
}

const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteChildren: protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteChildren =
  {
    protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute:
      protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute,
    protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute:
      protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsIndexRoute,
    protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute:
      protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsDiscussionIdIndexRoute,
    protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute:
      protectedLayoutCoursesCourseIdAssignmentsAssignmentIdDiscussionsCreateIndexRoute,
  }

const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteWithChildren =
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute._addFileChildren(
    protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteChildren,
  )

interface protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteChildren {
  protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute
  protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute
  protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute
}

const protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteChildren: protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteChildren =
  {
    protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute:
      protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsIndexRoute,
    protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute:
      protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsDiscussionIdIndexRoute,
    protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute:
      protectedLayoutCoursesCourseIdLecturesLectureIdDiscussionsCreateIndexRoute,
  }

const protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteWithChildren =
  protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute._addFileChildren(
    protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteChildren,
  )

interface protectedLayoutRouteRouteChildren {
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutAnnouncementsIndexRoute: typeof protectedLayoutAnnouncementsIndexRoute
  protectedLayoutBookmarkIndexRoute: typeof protectedLayoutBookmarkIndexRoute
  protectedLayoutChatIndexRoute: typeof protectedLayoutChatIndexRoute
  protectedLayoutCoursesIndexRoute: typeof protectedLayoutCoursesIndexRoute
  protectedLayoutDiscussionsIndexRoute: typeof protectedLayoutDiscussionsIndexRoute
  protectedLayoutMasaiverseIndexRoute: typeof protectedLayoutMasaiverseIndexRoute
  protectedLayoutPracticeInterviewIndexRoute: typeof protectedLayoutPracticeInterviewIndexRoute
  protectedLayoutProfileIndexRoute: typeof protectedLayoutProfileIndexRoute
  protectedLayoutReferAndEarnIndexRoute: typeof protectedLayoutReferAndEarnIndexRoute
  protectedLayoutSupportIndexRoute: typeof protectedLayoutSupportIndexRoute
  protectedLayoutWhatsNewIndexRoute: typeof protectedLayoutWhatsNewIndexRoute
  protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute: typeof protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteWithChildren
  protectedLayoutDiscussionsDiscussionIdIndexRoute: typeof protectedLayoutDiscussionsDiscussionIdIndexRoute
  protectedLayoutDiscussionsCreateIndexRoute: typeof protectedLayoutDiscussionsCreateIndexRoute
  protectedLayoutSupportSupportIdIndexRoute: typeof protectedLayoutSupportSupportIdIndexRoute
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteWithChildren
  protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteWithChildren
  protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute: typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute: typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
}

const protectedLayoutRouteRouteChildren: protectedLayoutRouteRouteChildren = {
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutAnnouncementsIndexRoute:
    protectedLayoutAnnouncementsIndexRoute,
  protectedLayoutBookmarkIndexRoute: protectedLayoutBookmarkIndexRoute,
  protectedLayoutChatIndexRoute: protectedLayoutChatIndexRoute,
  protectedLayoutCoursesIndexRoute: protectedLayoutCoursesIndexRoute,
  protectedLayoutDiscussionsIndexRoute: protectedLayoutDiscussionsIndexRoute,
  protectedLayoutMasaiverseIndexRoute: protectedLayoutMasaiverseIndexRoute,
  protectedLayoutPracticeInterviewIndexRoute:
    protectedLayoutPracticeInterviewIndexRoute,
  protectedLayoutProfileIndexRoute: protectedLayoutProfileIndexRoute,
  protectedLayoutReferAndEarnIndexRoute: protectedLayoutReferAndEarnIndexRoute,
  protectedLayoutSupportIndexRoute: protectedLayoutSupportIndexRoute,
  protectedLayoutWhatsNewIndexRoute: protectedLayoutWhatsNewIndexRoute,
  protectedLayoutCoursesCourseIdCourseTabLayoutRouteRoute:
    protectedLayoutCoursesCourseIdCourseTabLayoutRouteRouteWithChildren,
  protectedLayoutDiscussionsDiscussionIdIndexRoute:
    protectedLayoutDiscussionsDiscussionIdIndexRoute,
  protectedLayoutDiscussionsCreateIndexRoute:
    protectedLayoutDiscussionsCreateIndexRoute,
  protectedLayoutSupportSupportIdIndexRoute:
    protectedLayoutSupportSupportIdIndexRoute,
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRoute:
    protectedLayoutCoursesCourseIdAssignmentsAssignmentIdRouteRouteWithChildren,
  protectedLayoutCoursesCourseIdLecturesLectureIdRouteRoute:
    protectedLayoutCoursesCourseIdLecturesLectureIdRouteRouteWithChildren,
  protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute:
    protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute,
  protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute:
    protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute,
}

const protectedLayoutRouteRouteWithChildren =
  protectedLayoutRouteRoute._addFileChildren(protectedLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRouteRoute: protectedLayoutRouteRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
