/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteRouteImport } from './routes/(protected)/_layout/route'
import { Route as protectedLayoutIndexRouteImport } from './routes/(protected)/_layout/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as protectedLayoutSupportIndexRouteImport } from './routes/(protected)/_layout/support/index'
import { Route as protectedLayoutResourcesIndexRouteImport } from './routes/(protected)/_layout/resources/index'
import { Route as protectedLayoutLecturesIndexRouteImport } from './routes/(protected)/_layout/lectures/index'
import { Route as protectedLayoutCoursesIndexRouteImport } from './routes/(protected)/_layout/courses/index'
import { Route as protectedLayoutAssignmentsIndexRouteImport } from './routes/(protected)/_layout/assignments/index'
import { Route as protectedLayoutAnnouncementsIndexRouteImport } from './routes/(protected)/_layout/announcements/index'
import { Route as protectedLayoutCoursesCourseIdRouteRouteImport } from './routes/(protected)/_layout/courses/$courseId/route'
import { Route as protectedLayoutCoursesCourseIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/index'
import { Route as protectedLayoutCoursesCourseIdResourcesIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/resources/index'
import { Route as protectedLayoutCoursesCourseIdLecturesIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/lectures/index'
import { Route as protectedLayoutCoursesCourseIdDiscussionsIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/discussions/index'
import { Route as protectedLayoutCoursesCourseIdAssignmentsIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/assignments/index'
import { Route as protectedLayoutCoursesCourseIdAnnouncementsIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/announcements/index'
import { Route as protectedLayoutCoursesCourseIdResourcesResourceIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/resources/$resourceId/index'
import { Route as protectedLayoutCoursesCourseIdLecturesLectureIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/lectures/$lectureId/index'
import { Route as protectedLayoutCoursesCourseIdDiscussionsCreateIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/discussions/create/index'
import { Route as protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/discussions/$discussionId/index'
import { Route as protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/assignments/$assignmentId/index'
import { Route as protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRouteImport } from './routes/(protected)/_layout/courses/$courseId/announcements/$announcementId/index'

const protectedLayoutRouteRoute = protectedLayoutRouteRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutSupportIndexRoute =
  protectedLayoutSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutResourcesIndexRoute =
  protectedLayoutResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutLecturesIndexRoute =
  protectedLayoutLecturesIndexRouteImport.update({
    id: '/lectures/',
    path: '/lectures/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesIndexRoute =
  protectedLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutAssignmentsIndexRoute =
  protectedLayoutAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutAnnouncementsIndexRoute =
  protectedLayoutAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdRouteRoute =
  protectedLayoutCoursesCourseIdRouteRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdIndexRoute =
  protectedLayoutCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdResourcesIndexRoute =
  protectedLayoutCoursesCourseIdResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdLecturesIndexRoute =
  protectedLayoutCoursesCourseIdLecturesIndexRouteImport.update({
    id: '/lectures/',
    path: '/lectures/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdDiscussionsIndexRoute =
  protectedLayoutCoursesCourseIdDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdAssignmentsIndexRoute =
  protectedLayoutCoursesCourseIdAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdAnnouncementsIndexRoute =
  protectedLayoutCoursesCourseIdAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute =
  protectedLayoutCoursesCourseIdResourcesResourceIdIndexRouteImport.update({
    id: '/resources/$resourceId/',
    path: '/resources/$resourceId/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute =
  protectedLayoutCoursesCourseIdLecturesLectureIdIndexRouteImport.update({
    id: '/lectures/$lectureId/',
    path: '/lectures/$lectureId/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute =
  protectedLayoutCoursesCourseIdDiscussionsCreateIndexRouteImport.update({
    id: '/discussions/create/',
    path: '/discussions/create/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute =
  protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRouteImport.update({
    id: '/discussions/$discussionId/',
    path: '/discussions/$discussionId/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute =
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRouteImport.update({
    id: '/assignments/$assignmentId/',
    path: '/assignments/$assignmentId/',
    getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
  } as any)
const protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute =
  protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRouteImport.update(
    {
      id: '/announcements/$announcementId/',
      path: '/announcements/$announcementId/',
      getParentRoute: () => protectedLayoutCoursesCourseIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/login/': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/courses/$courseId': typeof protectedLayoutCoursesCourseIdRouteRouteWithChildren
  '/announcements/': typeof protectedLayoutAnnouncementsIndexRoute
  '/assignments/': typeof protectedLayoutAssignmentsIndexRoute
  '/courses/': typeof protectedLayoutCoursesIndexRoute
  '/lectures/': typeof protectedLayoutLecturesIndexRoute
  '/resources/': typeof protectedLayoutResourcesIndexRoute
  '/support/': typeof protectedLayoutSupportIndexRoute
  '/courses/$courseId/': typeof protectedLayoutCoursesCourseIdIndexRoute
  '/courses/$courseId/announcements/': typeof protectedLayoutCoursesCourseIdAnnouncementsIndexRoute
  '/courses/$courseId/assignments/': typeof protectedLayoutCoursesCourseIdAssignmentsIndexRoute
  '/courses/$courseId/discussions/': typeof protectedLayoutCoursesCourseIdDiscussionsIndexRoute
  '/courses/$courseId/lectures/': typeof protectedLayoutCoursesCourseIdLecturesIndexRoute
  '/courses/$courseId/resources/': typeof protectedLayoutCoursesCourseIdResourcesIndexRoute
  '/courses/$courseId/announcements/$announcementId/': typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  '/courses/$courseId/discussions/$discussionId/': typeof protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute
  '/courses/$courseId/discussions/create/': typeof protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute
  '/courses/$courseId/lectures/$lectureId/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute
  '/courses/$courseId/resources/$resourceId/': typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/announcements': typeof protectedLayoutAnnouncementsIndexRoute
  '/assignments': typeof protectedLayoutAssignmentsIndexRoute
  '/courses': typeof protectedLayoutCoursesIndexRoute
  '/lectures': typeof protectedLayoutLecturesIndexRoute
  '/resources': typeof protectedLayoutResourcesIndexRoute
  '/support': typeof protectedLayoutSupportIndexRoute
  '/courses/$courseId': typeof protectedLayoutCoursesCourseIdIndexRoute
  '/courses/$courseId/announcements': typeof protectedLayoutCoursesCourseIdAnnouncementsIndexRoute
  '/courses/$courseId/assignments': typeof protectedLayoutCoursesCourseIdAssignmentsIndexRoute
  '/courses/$courseId/discussions': typeof protectedLayoutCoursesCourseIdDiscussionsIndexRoute
  '/courses/$courseId/lectures': typeof protectedLayoutCoursesCourseIdLecturesIndexRoute
  '/courses/$courseId/resources': typeof protectedLayoutCoursesCourseIdResourcesIndexRoute
  '/courses/$courseId/announcements/$announcementId': typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  '/courses/$courseId/assignments/$assignmentId': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  '/courses/$courseId/discussions/$discussionId': typeof protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute
  '/courses/$courseId/discussions/create': typeof protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute
  '/courses/$courseId/lectures/$lectureId': typeof protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute
  '/courses/$courseId/resources/$resourceId': typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/_layout': typeof protectedLayoutRouteRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/_layout/courses/$courseId': typeof protectedLayoutCoursesCourseIdRouteRouteWithChildren
  '/(protected)/_layout/announcements/': typeof protectedLayoutAnnouncementsIndexRoute
  '/(protected)/_layout/assignments/': typeof protectedLayoutAssignmentsIndexRoute
  '/(protected)/_layout/courses/': typeof protectedLayoutCoursesIndexRoute
  '/(protected)/_layout/lectures/': typeof protectedLayoutLecturesIndexRoute
  '/(protected)/_layout/resources/': typeof protectedLayoutResourcesIndexRoute
  '/(protected)/_layout/support/': typeof protectedLayoutSupportIndexRoute
  '/(protected)/_layout/courses/$courseId/': typeof protectedLayoutCoursesCourseIdIndexRoute
  '/(protected)/_layout/courses/$courseId/announcements/': typeof protectedLayoutCoursesCourseIdAnnouncementsIndexRoute
  '/(protected)/_layout/courses/$courseId/assignments/': typeof protectedLayoutCoursesCourseIdAssignmentsIndexRoute
  '/(protected)/_layout/courses/$courseId/discussions/': typeof protectedLayoutCoursesCourseIdDiscussionsIndexRoute
  '/(protected)/_layout/courses/$courseId/lectures/': typeof protectedLayoutCoursesCourseIdLecturesIndexRoute
  '/(protected)/_layout/courses/$courseId/resources/': typeof protectedLayoutCoursesCourseIdResourcesIndexRoute
  '/(protected)/_layout/courses/$courseId/announcements/$announcementId/': typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  '/(protected)/_layout/courses/$courseId/assignments/$assignmentId/': typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  '/(protected)/_layout/courses/$courseId/discussions/$discussionId/': typeof protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute
  '/(protected)/_layout/courses/$courseId/discussions/create/': typeof protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute
  '/(protected)/_layout/courses/$courseId/lectures/$lectureId/': typeof protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute
  '/(protected)/_layout/courses/$courseId/resources/$resourceId/': typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login/'
    | '/'
    | '/courses/$courseId'
    | '/announcements/'
    | '/assignments/'
    | '/courses/'
    | '/lectures/'
    | '/resources/'
    | '/support/'
    | '/courses/$courseId/'
    | '/courses/$courseId/announcements/'
    | '/courses/$courseId/assignments/'
    | '/courses/$courseId/discussions/'
    | '/courses/$courseId/lectures/'
    | '/courses/$courseId/resources/'
    | '/courses/$courseId/announcements/$announcementId/'
    | '/courses/$courseId/assignments/$assignmentId/'
    | '/courses/$courseId/discussions/$discussionId/'
    | '/courses/$courseId/discussions/create/'
    | '/courses/$courseId/lectures/$lectureId/'
    | '/courses/$courseId/resources/$resourceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/announcements'
    | '/assignments'
    | '/courses'
    | '/lectures'
    | '/resources'
    | '/support'
    | '/courses/$courseId'
    | '/courses/$courseId/announcements'
    | '/courses/$courseId/assignments'
    | '/courses/$courseId/discussions'
    | '/courses/$courseId/lectures'
    | '/courses/$courseId/resources'
    | '/courses/$courseId/announcements/$announcementId'
    | '/courses/$courseId/assignments/$assignmentId'
    | '/courses/$courseId/discussions/$discussionId'
    | '/courses/$courseId/discussions/create'
    | '/courses/$courseId/lectures/$lectureId'
    | '/courses/$courseId/resources/$resourceId'
  id:
    | '__root__'
    | '/(protected)/_layout'
    | '/(auth)/login/'
    | '/(protected)/_layout/'
    | '/(protected)/_layout/courses/$courseId'
    | '/(protected)/_layout/announcements/'
    | '/(protected)/_layout/assignments/'
    | '/(protected)/_layout/courses/'
    | '/(protected)/_layout/lectures/'
    | '/(protected)/_layout/resources/'
    | '/(protected)/_layout/support/'
    | '/(protected)/_layout/courses/$courseId/'
    | '/(protected)/_layout/courses/$courseId/announcements/'
    | '/(protected)/_layout/courses/$courseId/assignments/'
    | '/(protected)/_layout/courses/$courseId/discussions/'
    | '/(protected)/_layout/courses/$courseId/lectures/'
    | '/(protected)/_layout/courses/$courseId/resources/'
    | '/(protected)/_layout/courses/$courseId/announcements/$announcementId/'
    | '/(protected)/_layout/courses/$courseId/assignments/$assignmentId/'
    | '/(protected)/_layout/courses/$courseId/discussions/$discussionId/'
    | '/(protected)/_layout/courses/$courseId/discussions/create/'
    | '/(protected)/_layout/courses/$courseId/lectures/$lectureId/'
    | '/(protected)/_layout/courses/$courseId/resources/$resourceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRouteRoute: typeof protectedLayoutRouteRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/support/': {
      id: '/(protected)/_layout/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof protectedLayoutSupportIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/resources/': {
      id: '/(protected)/_layout/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof protectedLayoutResourcesIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/lectures/': {
      id: '/(protected)/_layout/lectures/'
      path: '/lectures'
      fullPath: '/lectures/'
      preLoaderRoute: typeof protectedLayoutLecturesIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/': {
      id: '/(protected)/_layout/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof protectedLayoutCoursesIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/assignments/': {
      id: '/(protected)/_layout/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof protectedLayoutAssignmentsIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/announcements/': {
      id: '/(protected)/_layout/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof protectedLayoutAnnouncementsIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId': {
      id: '/(protected)/_layout/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/': {
      id: '/(protected)/_layout/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/resources/': {
      id: '/(protected)/_layout/courses/$courseId/resources/'
      path: '/resources'
      fullPath: '/courses/$courseId/resources/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdResourcesIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/lectures/': {
      id: '/(protected)/_layout/courses/$courseId/lectures/'
      path: '/lectures'
      fullPath: '/courses/$courseId/lectures/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdLecturesIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/discussions/': {
      id: '/(protected)/_layout/courses/$courseId/discussions/'
      path: '/discussions'
      fullPath: '/courses/$courseId/discussions/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdDiscussionsIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/assignments/': {
      id: '/(protected)/_layout/courses/$courseId/assignments/'
      path: '/assignments'
      fullPath: '/courses/$courseId/assignments/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAssignmentsIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/announcements/': {
      id: '/(protected)/_layout/courses/$courseId/announcements/'
      path: '/announcements'
      fullPath: '/courses/$courseId/announcements/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAnnouncementsIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/resources/$resourceId/': {
      id: '/(protected)/_layout/courses/$courseId/resources/$resourceId/'
      path: '/resources/$resourceId'
      fullPath: '/courses/$courseId/resources/$resourceId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/lectures/$lectureId/': {
      id: '/(protected)/_layout/courses/$courseId/lectures/$lectureId/'
      path: '/lectures/$lectureId'
      fullPath: '/courses/$courseId/lectures/$lectureId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/discussions/create/': {
      id: '/(protected)/_layout/courses/$courseId/discussions/create/'
      path: '/discussions/create'
      fullPath: '/courses/$courseId/discussions/create/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdDiscussionsCreateIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/discussions/$discussionId/': {
      id: '/(protected)/_layout/courses/$courseId/discussions/$discussionId/'
      path: '/discussions/$discussionId'
      fullPath: '/courses/$courseId/discussions/$discussionId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/assignments/$assignmentId/': {
      id: '/(protected)/_layout/courses/$courseId/assignments/$assignmentId/'
      path: '/assignments/$assignmentId'
      fullPath: '/courses/$courseId/assignments/$assignmentId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
    '/(protected)/_layout/courses/$courseId/announcements/$announcementId/': {
      id: '/(protected)/_layout/courses/$courseId/announcements/$announcementId/'
      path: '/announcements/$announcementId'
      fullPath: '/courses/$courseId/announcements/$announcementId/'
      preLoaderRoute: typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRouteImport
      parentRoute: typeof protectedLayoutCoursesCourseIdRouteRoute
    }
  }
}

interface protectedLayoutCoursesCourseIdRouteRouteChildren {
  protectedLayoutCoursesCourseIdIndexRoute: typeof protectedLayoutCoursesCourseIdIndexRoute
  protectedLayoutCoursesCourseIdAnnouncementsIndexRoute: typeof protectedLayoutCoursesCourseIdAnnouncementsIndexRoute
  protectedLayoutCoursesCourseIdAssignmentsIndexRoute: typeof protectedLayoutCoursesCourseIdAssignmentsIndexRoute
  protectedLayoutCoursesCourseIdDiscussionsIndexRoute: typeof protectedLayoutCoursesCourseIdDiscussionsIndexRoute
  protectedLayoutCoursesCourseIdLecturesIndexRoute: typeof protectedLayoutCoursesCourseIdLecturesIndexRoute
  protectedLayoutCoursesCourseIdResourcesIndexRoute: typeof protectedLayoutCoursesCourseIdResourcesIndexRoute
  protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute: typeof protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute
  protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute: typeof protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute
  protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute: typeof protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute
  protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute: typeof protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute
  protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute: typeof protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute
  protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute: typeof protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute
}

const protectedLayoutCoursesCourseIdRouteRouteChildren: protectedLayoutCoursesCourseIdRouteRouteChildren =
  {
    protectedLayoutCoursesCourseIdIndexRoute:
      protectedLayoutCoursesCourseIdIndexRoute,
    protectedLayoutCoursesCourseIdAnnouncementsIndexRoute:
      protectedLayoutCoursesCourseIdAnnouncementsIndexRoute,
    protectedLayoutCoursesCourseIdAssignmentsIndexRoute:
      protectedLayoutCoursesCourseIdAssignmentsIndexRoute,
    protectedLayoutCoursesCourseIdDiscussionsIndexRoute:
      protectedLayoutCoursesCourseIdDiscussionsIndexRoute,
    protectedLayoutCoursesCourseIdLecturesIndexRoute:
      protectedLayoutCoursesCourseIdLecturesIndexRoute,
    protectedLayoutCoursesCourseIdResourcesIndexRoute:
      protectedLayoutCoursesCourseIdResourcesIndexRoute,
    protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute:
      protectedLayoutCoursesCourseIdAnnouncementsAnnouncementIdIndexRoute,
    protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute:
      protectedLayoutCoursesCourseIdAssignmentsAssignmentIdIndexRoute,
    protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute:
      protectedLayoutCoursesCourseIdDiscussionsDiscussionIdIndexRoute,
    protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute:
      protectedLayoutCoursesCourseIdDiscussionsCreateIndexRoute,
    protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute:
      protectedLayoutCoursesCourseIdLecturesLectureIdIndexRoute,
    protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute:
      protectedLayoutCoursesCourseIdResourcesResourceIdIndexRoute,
  }

const protectedLayoutCoursesCourseIdRouteRouteWithChildren =
  protectedLayoutCoursesCourseIdRouteRoute._addFileChildren(
    protectedLayoutCoursesCourseIdRouteRouteChildren,
  )

interface protectedLayoutRouteRouteChildren {
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutCoursesCourseIdRouteRoute: typeof protectedLayoutCoursesCourseIdRouteRouteWithChildren
  protectedLayoutAnnouncementsIndexRoute: typeof protectedLayoutAnnouncementsIndexRoute
  protectedLayoutAssignmentsIndexRoute: typeof protectedLayoutAssignmentsIndexRoute
  protectedLayoutCoursesIndexRoute: typeof protectedLayoutCoursesIndexRoute
  protectedLayoutLecturesIndexRoute: typeof protectedLayoutLecturesIndexRoute
  protectedLayoutResourcesIndexRoute: typeof protectedLayoutResourcesIndexRoute
  protectedLayoutSupportIndexRoute: typeof protectedLayoutSupportIndexRoute
}

const protectedLayoutRouteRouteChildren: protectedLayoutRouteRouteChildren = {
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutCoursesCourseIdRouteRoute:
    protectedLayoutCoursesCourseIdRouteRouteWithChildren,
  protectedLayoutAnnouncementsIndexRoute:
    protectedLayoutAnnouncementsIndexRoute,
  protectedLayoutAssignmentsIndexRoute: protectedLayoutAssignmentsIndexRoute,
  protectedLayoutCoursesIndexRoute: protectedLayoutCoursesIndexRoute,
  protectedLayoutLecturesIndexRoute: protectedLayoutLecturesIndexRoute,
  protectedLayoutResourcesIndexRoute: protectedLayoutResourcesIndexRoute,
  protectedLayoutSupportIndexRoute: protectedLayoutSupportIndexRoute,
}

const protectedLayoutRouteRouteWithChildren =
  protectedLayoutRouteRoute._addFileChildren(protectedLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRouteRoute: protectedLayoutRouteRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
